disabled_rules:
- trailing_whitespace
- file_length
- line_length
- force_cast
- cyclomatic_complexity
- multiple_closures_with_trailing_closure
- identifier_name

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 8
    error: 10

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

reporter: "xcode"

custom_rules:
pirates_beat_ninjas: # rule identifier
  included: ".*\\.swift" # regex that defines paths to include during linting. optional.
  excluded: ".*Test\\.swift" # regex that defines paths to exclude during linting. optional
  name: "Pirates Beat Ninjas" # rule name. optional.
  regex: "([n,N]inja)" # matching pattern
  match_kinds: # SyntaxKinds to match. optional.
    - comment
    - identifier
  message: "Pirates are better than ninjas." # violation message. optional.
  severity: error # violation severity. optional.
no_hiding_in_strings:
  regex: "([n,N]inja)"
  match_kinds: string
